import { Task } from './types';

const now = new Date();
const daysAgo = (n: number) => new Date(now.getTime() - n * 24 * 60 * 60 * 1000).toISOString();
const daysFromNow = (n: number) => new Date(now.getTime() + n * 24 * 60 * 60 * 1000).toISOString();

export const sampleTasks: Task[] = [
  {
    id: '1',
    title: 'Design new landing page',
    description: 'Create wireframes and mockups for the new marketing landing page with modern glassmorphism design.',
    status: 'completed',
    priority: 'high',
    category: 'Design',
    dueDate: daysAgo(2),
    createdAt: daysAgo(10),
    updatedAt: daysAgo(2),
  },
  {
    id: '2',
    title: 'Implement user authentication',
    description: 'Set up NextAuth.js with Google and GitHub OAuth providers.',
    status: 'in-progress',
    priority: 'high',
    category: 'Development',
    dueDate: daysFromNow(3),
    createdAt: daysAgo(7),
    updatedAt: daysAgo(1),
  },
  {
    id: '3',
    title: 'Write API documentation',
    description: 'Document all REST API endpoints with request/response examples.',
    status: 'todo',
    priority: 'medium',
    category: 'Documentation',
    dueDate: daysFromNow(7),
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    id: '4',
    title: 'Fix checkout flow bug',
    description: 'Users are unable to complete checkout when using PayPal. Investigate and resolve.',
    status: 'in-progress',
    priority: 'high',
    category: 'Development',
    dueDate: daysFromNow(1),
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
  },
  {
    id: '5',
    title: 'Set up CI/CD pipeline',
    description: 'Configure GitHub Actions for automated testing and deployment.',
    status: 'completed',
    priority: 'medium',
    category: 'DevOps',
    dueDate: daysAgo(5),
    createdAt: daysAgo(14),
    updatedAt: daysAgo(5),
  },
  {
    id: '6',
    title: 'Conduct user interviews',
    description: 'Schedule and conduct 5 user interviews to gather feedback on the new dashboard.',
    status: 'todo',
    priority: 'medium',
    category: 'Research',
    dueDate: daysFromNow(10),
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
  },
  {
    id: '7',
    title: 'Optimize database queries',
    description: 'Profile slow queries and add appropriate indexes to improve performance.',
    status: 'todo',
    priority: 'high',
    category: 'Development',
    dueDate: daysFromNow(5),
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: '8',
    title: 'Update privacy policy',
    description: 'Review and update privacy policy to comply with new GDPR requirements.',
    status: 'completed',
    priority: 'low',
    category: 'Legal',
    dueDate: daysAgo(8),
    createdAt: daysAgo(15),
    updatedAt: daysAgo(8),
  },
  {
    id: '9',
    title: 'Mobile app beta testing',
    description: 'Coordinate beta testing program with 20 selected users.',
    status: 'in-progress',
    priority: 'medium',
    category: 'Testing',
    dueDate: daysFromNow(14),
    createdAt: daysAgo(6),
    updatedAt: daysAgo(2),
  },
  {
    id: '10',
    title: 'Create onboarding tutorial',
    description: 'Design and implement an interactive onboarding flow for new users.',
    status: 'todo',
    priority: 'low',
    category: 'Design',
    dueDate: daysFromNow(21),
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: '11',
    title: 'Security audit',
    description: 'Perform comprehensive security audit of the application.',
    status: 'todo',
    priority: 'high',
    category: 'DevOps',
    dueDate: daysAgo(1),
    createdAt: daysAgo(8),
    updatedAt: daysAgo(8),
  },
  {
    id: '12',
    title: 'Refactor payment module',
    description: 'Clean up legacy code in the payment processing module.',
    status: 'completed',
    priority: 'medium',
    category: 'Development',
    dueDate: daysAgo(3),
    createdAt: daysAgo(12),
    updatedAt: daysAgo(3),
  },
];

export const CATEGORIES = [
  'Design',
  'Development',
  'Documentation',
  'DevOps',
  'Research',
  'Testing',
  'Legal',
  'Marketing',
  'Other',
];
